// Generated by gencpp from file webcam/Tile_Message.msg
// DO NOT EDIT!


#ifndef WEBCAM_MESSAGE_TILE_MESSAGE_H
#define WEBCAM_MESSAGE_TILE_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webcam
{
template <class ContainerAllocator>
struct Tile_Message_
{
  typedef Tile_Message_<ContainerAllocator> Type;

  Tile_Message_()
    : x(0)
    , y(0)
    , color(0)  {
    }
  Tile_Message_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , color(0)  {
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _color_type;
  _color_type color;




  typedef boost::shared_ptr< ::webcam::Tile_Message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webcam::Tile_Message_<ContainerAllocator> const> ConstPtr;

}; // struct Tile_Message_

typedef ::webcam::Tile_Message_<std::allocator<void> > Tile_Message;

typedef boost::shared_ptr< ::webcam::Tile_Message > Tile_MessagePtr;
typedef boost::shared_ptr< ::webcam::Tile_Message const> Tile_MessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webcam::Tile_Message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webcam::Tile_Message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace webcam

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'webcam': ['/home/sanderkempen/Coding/Tesseron/src/webcam/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::webcam::Tile_Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webcam::Tile_Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webcam::Tile_Message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webcam::Tile_Message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webcam::Tile_Message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webcam::Tile_Message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webcam::Tile_Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba8f66fb9a826b4b4813256b892c0bf4";
  }

  static const char* value(const ::webcam::Tile_Message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba8f66fb9a826b4bULL;
  static const uint64_t static_value2 = 0x4813256b892c0bf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::webcam::Tile_Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webcam/Tile_Message";
  }

  static const char* value(const ::webcam::Tile_Message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webcam::Tile_Message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n\
int32 y\n\
int32 color\n\
";
  }

  static const char* value(const ::webcam::Tile_Message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webcam::Tile_Message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Tile_Message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webcam::Tile_Message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webcam::Tile_Message_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "color: ";
    Printer<int32_t>::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBCAM_MESSAGE_TILE_MESSAGE_H
