// Generated by gencpp from file gripper/PickUp.msg
// DO NOT EDIT!


#ifndef GRIPPER_MESSAGE_PICKUP_H
#define GRIPPER_MESSAGE_PICKUP_H

#include <ros/service_traits.h>


#include <gripper/PickUpRequest.h>
#include <gripper/PickUpResponse.h>


namespace gripper
{

struct PickUp
{

typedef PickUpRequest Request;
typedef PickUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickUp
} // namespace gripper


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gripper::PickUp > {
  static const char* value()
  {
    return "52707f1aa79bcb694bdb48d3cc3420b7";
  }

  static const char* value(const ::gripper::PickUp&) { return value(); }
};

template<>
struct DataType< ::gripper::PickUp > {
  static const char* value()
  {
    return "gripper/PickUp";
  }

  static const char* value(const ::gripper::PickUp&) { return value(); }
};


// service_traits::MD5Sum< ::gripper::PickUpRequest> should match 
// service_traits::MD5Sum< ::gripper::PickUp > 
template<>
struct MD5Sum< ::gripper::PickUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gripper::PickUp >::value();
  }
  static const char* value(const ::gripper::PickUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper::PickUpRequest> should match 
// service_traits::DataType< ::gripper::PickUp > 
template<>
struct DataType< ::gripper::PickUpRequest>
{
  static const char* value()
  {
    return DataType< ::gripper::PickUp >::value();
  }
  static const char* value(const ::gripper::PickUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gripper::PickUpResponse> should match 
// service_traits::MD5Sum< ::gripper::PickUp > 
template<>
struct MD5Sum< ::gripper::PickUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gripper::PickUp >::value();
  }
  static const char* value(const ::gripper::PickUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper::PickUpResponse> should match 
// service_traits::DataType< ::gripper::PickUp > 
template<>
struct DataType< ::gripper::PickUpResponse>
{
  static const char* value()
  {
    return DataType< ::gripper::PickUp >::value();
  }
  static const char* value(const ::gripper::PickUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRIPPER_MESSAGE_PICKUP_H
