// Generated by gencpp from file supervisor/ErrorMessage.msg
// DO NOT EDIT!


#ifndef SUPERVISOR_MESSAGE_ERRORMESSAGE_H
#define SUPERVISOR_MESSAGE_ERRORMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace supervisor
{
template <class ContainerAllocator>
struct ErrorMessage_
{
  typedef ErrorMessage_<ContainerAllocator> Type;

  ErrorMessage_()
    : sender()
    , error()  {
    }
  ErrorMessage_(const ContainerAllocator& _alloc)
    : sender(_alloc)
    , error(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  _sender_type sender;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_type;
  _error_type error;




  typedef boost::shared_ptr< ::supervisor::ErrorMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::supervisor::ErrorMessage_<ContainerAllocator> const> ConstPtr;

}; // struct ErrorMessage_

typedef ::supervisor::ErrorMessage_<std::allocator<void> > ErrorMessage;

typedef boost::shared_ptr< ::supervisor::ErrorMessage > ErrorMessagePtr;
typedef boost::shared_ptr< ::supervisor::ErrorMessage const> ErrorMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::supervisor::ErrorMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::supervisor::ErrorMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace supervisor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'supervisor': ['/home/newnottakenname/Coding/Tesseron/src/supervisor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::supervisor::ErrorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::supervisor::ErrorMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervisor::ErrorMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::supervisor::ErrorMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervisor::ErrorMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::supervisor::ErrorMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::supervisor::ErrorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9300fa2821338ec45a63faf095c9cefa";
  }

  static const char* value(const ::supervisor::ErrorMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9300fa2821338ec4ULL;
  static const uint64_t static_value2 = 0x5a63faf095c9cefaULL;
};

template<class ContainerAllocator>
struct DataType< ::supervisor::ErrorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "supervisor/ErrorMessage";
  }

  static const char* value(const ::supervisor::ErrorMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::supervisor::ErrorMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sender\n\
string error\n\
";
  }

  static const char* value(const ::supervisor::ErrorMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::supervisor::ErrorMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sender);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ErrorMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::supervisor::ErrorMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::supervisor::ErrorMessage_<ContainerAllocator>& v)
  {
    s << indent << "sender: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sender);
    s << indent << "error: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUPERVISOR_MESSAGE_ERRORMESSAGE_H
