// Generated by gencpp from file supervisor/PickUp.msg
// DO NOT EDIT!


#ifndef SUPERVISOR_MESSAGE_PICKUP_H
#define SUPERVISOR_MESSAGE_PICKUP_H

#include <ros/service_traits.h>


#include <supervisor/PickUpRequest.h>
#include <supervisor/PickUpResponse.h>


namespace supervisor
{

struct PickUp
{

typedef PickUpRequest Request;
typedef PickUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickUp
} // namespace supervisor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::supervisor::PickUp > {
  static const char* value()
  {
    return "52707f1aa79bcb694bdb48d3cc3420b7";
  }

  static const char* value(const ::supervisor::PickUp&) { return value(); }
};

template<>
struct DataType< ::supervisor::PickUp > {
  static const char* value()
  {
    return "supervisor/PickUp";
  }

  static const char* value(const ::supervisor::PickUp&) { return value(); }
};


// service_traits::MD5Sum< ::supervisor::PickUpRequest> should match 
// service_traits::MD5Sum< ::supervisor::PickUp > 
template<>
struct MD5Sum< ::supervisor::PickUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::supervisor::PickUp >::value();
  }
  static const char* value(const ::supervisor::PickUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::supervisor::PickUpRequest> should match 
// service_traits::DataType< ::supervisor::PickUp > 
template<>
struct DataType< ::supervisor::PickUpRequest>
{
  static const char* value()
  {
    return DataType< ::supervisor::PickUp >::value();
  }
  static const char* value(const ::supervisor::PickUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::supervisor::PickUpResponse> should match 
// service_traits::MD5Sum< ::supervisor::PickUp > 
template<>
struct MD5Sum< ::supervisor::PickUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::supervisor::PickUp >::value();
  }
  static const char* value(const ::supervisor::PickUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::supervisor::PickUpResponse> should match 
// service_traits::DataType< ::supervisor::PickUp > 
template<>
struct DataType< ::supervisor::PickUpResponse>
{
  static const char* value()
  {
    return DataType< ::supervisor::PickUp >::value();
  }
  static const char* value(const ::supervisor::PickUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUPERVISOR_MESSAGE_PICKUP_H
