// Generated by gencpp from file base_catkin/BaseStatus.msg
// DO NOT EDIT!


#ifndef BASE_CATKIN_MESSAGE_BASESTATUS_H
#define BASE_CATKIN_MESSAGE_BASESTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <base_catkin/MotorStatus.h>
#include <base_catkin/MotorStatus.h>

namespace base_catkin
{
template <class ContainerAllocator>
struct BaseStatus_
{
  typedef BaseStatus_<ContainerAllocator> Type;

  BaseStatus_()
    : left()
    , right()  {
    }
  BaseStatus_(const ContainerAllocator& _alloc)
    : left(_alloc)
    , right(_alloc)  {
    }



   typedef  ::base_catkin::MotorStatus_<ContainerAllocator>  _left_type;
  _left_type left;

   typedef  ::base_catkin::MotorStatus_<ContainerAllocator>  _right_type;
  _right_type right;




  typedef boost::shared_ptr< ::base_catkin::BaseStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_catkin::BaseStatus_<ContainerAllocator> const> ConstPtr;

}; // struct BaseStatus_

typedef ::base_catkin::BaseStatus_<std::allocator<void> > BaseStatus;

typedef boost::shared_ptr< ::base_catkin::BaseStatus > BaseStatusPtr;
typedef boost::shared_ptr< ::base_catkin::BaseStatus const> BaseStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_catkin::BaseStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_catkin::BaseStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_catkin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'base_catkin': ['/home/sanderkempen/Coding/Tesseron/src/base_catkin/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_catkin::BaseStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_catkin::BaseStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_catkin::BaseStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_catkin::BaseStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_catkin::BaseStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_catkin::BaseStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_catkin::BaseStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f988fbf67915d8c43f12862176bdea31";
  }

  static const char* value(const ::base_catkin::BaseStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf988fbf67915d8c4ULL;
  static const uint64_t static_value2 = 0x3f12862176bdea31ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_catkin::BaseStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_catkin/BaseStatus";
  }

  static const char* value(const ::base_catkin::BaseStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_catkin::BaseStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MotorStatus left\n\
MotorStatus right\n\
\n\
================================================================================\n\
MSG: base_catkin/MotorStatus\n\
float64 speed\n\
float64 position\n\
float64 torque\n\
int32 status\n\
";
  }

  static const char* value(const ::base_catkin::BaseStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_catkin::BaseStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BaseStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_catkin::BaseStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_catkin::BaseStatus_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    s << std::endl;
    Printer< ::base_catkin::MotorStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    s << std::endl;
    Printer< ::base_catkin::MotorStatus_<ContainerAllocator> >::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_CATKIN_MESSAGE_BASESTATUS_H
