// Generated by gencpp from file base_catkin/MotorStatus.msg
// DO NOT EDIT!


#ifndef BASE_CATKIN_MESSAGE_MOTORSTATUS_H
#define BASE_CATKIN_MESSAGE_MOTORSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_catkin
{
template <class ContainerAllocator>
struct MotorStatus_
{
  typedef MotorStatus_<ContainerAllocator> Type;

  MotorStatus_()
    : speed(0.0)
    , position(0.0)
    , torque(0.0)
    , status(0)  {
    }
  MotorStatus_(const ContainerAllocator& _alloc)
    : speed(0.0)
    , position(0.0)
    , torque(0.0)
    , status(0)  {
    }



   typedef double _speed_type;
  _speed_type speed;

   typedef double _position_type;
  _position_type position;

   typedef double _torque_type;
  _torque_type torque;

   typedef int32_t _status_type;
  _status_type status;




  typedef boost::shared_ptr< ::base_catkin::MotorStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_catkin::MotorStatus_<ContainerAllocator> const> ConstPtr;

}; // struct MotorStatus_

typedef ::base_catkin::MotorStatus_<std::allocator<void> > MotorStatus;

typedef boost::shared_ptr< ::base_catkin::MotorStatus > MotorStatusPtr;
typedef boost::shared_ptr< ::base_catkin::MotorStatus const> MotorStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_catkin::MotorStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_catkin::MotorStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_catkin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'base_catkin': ['/home/sanderkempen/Coding/Tesseron/src/base_catkin/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_catkin::MotorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_catkin::MotorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_catkin::MotorStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_catkin::MotorStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_catkin::MotorStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_catkin::MotorStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_catkin::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3080e3629e537b83f87bd84ba522d60";
  }

  static const char* value(const ::base_catkin::MotorStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3080e3629e537b8ULL;
  static const uint64_t static_value2 = 0x3f87bd84ba522d60ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_catkin::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_catkin/MotorStatus";
  }

  static const char* value(const ::base_catkin::MotorStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_catkin::MotorStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 speed\n\
float64 position\n\
float64 torque\n\
int32 status\n\
";
  }

  static const char* value(const ::base_catkin::MotorStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_catkin::MotorStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.position);
      stream.next(m.torque);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MotorStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_catkin::MotorStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_catkin::MotorStatus_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "torque: ";
    Printer<double>::stream(s, indent + "  ", v.torque);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_CATKIN_MESSAGE_MOTORSTATUS_H
