// Generated by gencpp from file base_catkin/WheelRequest.msg
// DO NOT EDIT!


#ifndef BASE_CATKIN_MESSAGE_WHEELREQUEST_H
#define BASE_CATKIN_MESSAGE_WHEELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_catkin
{
template <class ContainerAllocator>
struct WheelRequest_
{
  typedef WheelRequest_<ContainerAllocator> Type;

  WheelRequest_()
    : distance(0.0)  {
    }
  WheelRequest_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
    }



   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::base_catkin::WheelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_catkin::WheelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WheelRequest_

typedef ::base_catkin::WheelRequest_<std::allocator<void> > WheelRequest;

typedef boost::shared_ptr< ::base_catkin::WheelRequest > WheelRequestPtr;
typedef boost::shared_ptr< ::base_catkin::WheelRequest const> WheelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_catkin::WheelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_catkin::WheelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_catkin

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'base_catkin': ['/home/sanderkempen/Coding/Tesseron/src/base_catkin/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_catkin::WheelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_catkin::WheelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_catkin::WheelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_catkin::WheelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_catkin::WheelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_catkin::WheelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_catkin::WheelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::base_catkin::WheelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_catkin::WheelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_catkin/WheelRequest";
  }

  static const char* value(const ::base_catkin::WheelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_catkin::WheelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
";
  }

  static const char* value(const ::base_catkin::WheelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_catkin::WheelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct WheelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_catkin::WheelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_catkin::WheelRequest_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_CATKIN_MESSAGE_WHEELREQUEST_H
