// Generated by gencpp from file base_catkin/Wheel.msg
// DO NOT EDIT!


#ifndef BASE_CATKIN_MESSAGE_WHEEL_H
#define BASE_CATKIN_MESSAGE_WHEEL_H

#include <ros/service_traits.h>


#include <base_catkin/WheelRequest.h>
#include <base_catkin/WheelResponse.h>


namespace base_catkin
{

struct Wheel
{

typedef WheelRequest Request;
typedef WheelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wheel
} // namespace base_catkin


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_catkin::Wheel > {
  static const char* value()
  {
    return "d20927af59529502236f1660ce633198";
  }

  static const char* value(const ::base_catkin::Wheel&) { return value(); }
};

template<>
struct DataType< ::base_catkin::Wheel > {
  static const char* value()
  {
    return "base_catkin/Wheel";
  }

  static const char* value(const ::base_catkin::Wheel&) { return value(); }
};


// service_traits::MD5Sum< ::base_catkin::WheelRequest> should match 
// service_traits::MD5Sum< ::base_catkin::Wheel > 
template<>
struct MD5Sum< ::base_catkin::WheelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_catkin::Wheel >::value();
  }
  static const char* value(const ::base_catkin::WheelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_catkin::WheelRequest> should match 
// service_traits::DataType< ::base_catkin::Wheel > 
template<>
struct DataType< ::base_catkin::WheelRequest>
{
  static const char* value()
  {
    return DataType< ::base_catkin::Wheel >::value();
  }
  static const char* value(const ::base_catkin::WheelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_catkin::WheelResponse> should match 
// service_traits::MD5Sum< ::base_catkin::Wheel > 
template<>
struct MD5Sum< ::base_catkin::WheelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_catkin::Wheel >::value();
  }
  static const char* value(const ::base_catkin::WheelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_catkin::WheelResponse> should match 
// service_traits::DataType< ::base_catkin::Wheel > 
template<>
struct DataType< ::base_catkin::WheelResponse>
{
  static const char* value()
  {
    return DataType< ::base_catkin::Wheel >::value();
  }
  static const char* value(const ::base_catkin::WheelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_CATKIN_MESSAGE_WHEEL_H
